<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:v="http://javai.org/verdict/1.0"
                exclude-result-prefixes="v">

  <xsl:output method="html" encoding="UTF-8" indent="yes"
              doctype-system="about:legacy-compat"/>

  <!-- ===================================================================
       Root template
       =================================================================== -->

  <xsl:template match="/v:verdict-suite">
    <html lang="en">
      <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <title>feotest Report</title>
        <xsl:call-template name="css"/>
      </head>
      <body>
        <xsl:call-template name="header"/>
        <xsl:call-template name="assumptions"/>
        <main>
          <xsl:call-template name="groups"/>
        </main>
        <footer>
          <xsl:text>Generated by feotest</xsl:text>
          <xsl:if test="@timestamp">
            <xsl:text> at </xsl:text>
            <xsl:value-of select="@timestamp"/>
          </xsl:if>
        </footer>
      </body>
    </html>
  </xsl:template>

  <!-- ===================================================================
       Header with summary stats
       =================================================================== -->

  <xsl:template name="header">
    <header>
      <h1>feotest Report</h1>
      <xsl:if test="@timestamp">
        <p class="timestamp">
          <xsl:text>Generated: </xsl:text>
          <xsl:value-of select="@timestamp"/>
        </p>
      </xsl:if>

      <xsl:variable name="total" select="count(v:verdict-record)"/>
      <xsl:variable name="pass" select="count(v:verdict-record[v:verdict/@value='PASS'])"/>
      <xsl:variable name="fail" select="count(v:verdict-record[v:verdict/@value='FAIL'])"/>
      <xsl:variable name="inconclusive" select="$total - $pass - $fail"/>

      <div class="summary-stats">
        <xsl:text>Total: </xsl:text><xsl:value-of select="$total"/>
        <xsl:text> | </xsl:text>
        <span class="pass">Pass: <xsl:value-of select="$pass"/></span>
        <xsl:text> | </xsl:text>
        <span class="fail">Fail: <xsl:value-of select="$fail"/></span>
        <xsl:text> | </xsl:text>
        <span class="inconclusive">Inconclusive: <xsl:value-of select="$inconclusive"/></span>
      </div>

      <xsl:if test="$inconclusive &gt; 0">
        <div class="inconclusive-banner">
          <strong>
            <xsl:value-of select="$inconclusive"/>
            <xsl:text> inconclusive verdict</xsl:text>
            <xsl:if test="$inconclusive &gt; 1">s</xsl:if>
          </strong>
          <xsl:text> &#x2014; statistical analysis could not be relied upon. </xsl:text>
          <xsl:text>Consider re-running experiments with </xsl:text>
          <code>cargo test</code>
          <xsl:text> to re-establish baselines under current conditions.</xsl:text>
        </div>
      </xsl:if>
    </header>
  </xsl:template>

  <!-- ===================================================================
       Statistical assumptions (collapsible)
       =================================================================== -->

  <xsl:template name="assumptions">
    <details class="assumptions">
      <summary>Statistical assumptions and limitations</summary>
      <div class="content">
        <ul>
          <li><strong>Binary outcome:</strong> Each trial produces a success or failure. The framework models this as a Bernoulli experiment.</li>
          <li><strong>Same question each time:</strong> Every trial must exercise the same input distribution and contract. Mixing different queries into a single test invalidates the statistical model.</li>
          <li><strong>Unchanged threshold:</strong> The pass/fail threshold is fixed before trials begin. Adjusting the threshold after observing results is a form of p-hacking.</li>
          <li><strong>Independence:</strong> Trials are assumed to be independent. Shared caches, rate limits, or model warm-up can introduce dependency. The warm-up mechanism mitigates some of this, but cannot eliminate all sources.</li>
          <li><strong>No major drift:</strong> The service is assumed to be stationary during the test run. If the provider deploys a new model version mid-run, results may be unreliable.</li>
        </ul>
      </div>
    </details>
  </xsl:template>

  <!-- ===================================================================
       Group by use-case-id
       =================================================================== -->

  <xsl:template name="groups">
    <!-- Muenchian grouping by use-case-id -->
    <xsl:for-each select="v:verdict-record[not(v:identity/@use-case-id = preceding-sibling::v:verdict-record/v:identity/@use-case-id)]">
      <xsl:variable name="group-id" select="v:identity/@use-case-id"/>
      <section class="test-group">
        <h2><xsl:value-of select="$group-id"/></h2>
        <table>
          <thead>
            <tr>
              <th>Test Name</th>
              <th>Verdict</th>
              <th>Functional</th>
              <th>p50</th>
              <th>p95</th>
              <th>p99</th>
              <th>Samples</th>
              <th>Elapsed</th>
            </tr>
          </thead>
          <tbody>
            <xsl:for-each select="/v:verdict-suite/v:verdict-record[v:identity/@use-case-id = $group-id]">
              <xsl:call-template name="verdict-row"/>
            </xsl:for-each>
          </tbody>
        </table>
      </section>
    </xsl:for-each>
  </xsl:template>

  <!-- ===================================================================
       Verdict row (summary + expandable detail)
       =================================================================== -->

  <xsl:template name="verdict-row">
    <xsl:variable name="test-name">
      <xsl:choose>
        <xsl:when test="v:identity/@test-name">
          <xsl:value-of select="v:identity/@test-name"/>
        </xsl:when>
        <xsl:otherwise>
          <xsl:value-of select="v:identity/@use-case-id"/>
        </xsl:otherwise>
      </xsl:choose>
    </xsl:variable>

    <xsl:variable name="verdict-value" select="v:verdict/@value"/>
    <xsl:variable name="verdict-class">
      <xsl:choose>
        <xsl:when test="$verdict-value='PASS'">verdict-pass</xsl:when>
        <xsl:when test="$verdict-value='FAIL'">verdict-fail</xsl:when>
        <xsl:otherwise>verdict-inconclusive</xsl:otherwise>
      </xsl:choose>
    </xsl:variable>

    <!-- Summary row -->
    <tr>
      <td><xsl:value-of select="$test-name"/></td>
      <td class="{$verdict-class}"><xsl:value-of select="$verdict-value"/></td>
      <td>
        <xsl:value-of select="v:functional/@successes"/>
        <xsl:text>/</xsl:text>
        <xsl:value-of select="v:functional/@successes + v:functional/@failures"/>
        <xsl:text> (</xsl:text>
        <xsl:value-of select="v:functional/@pass-rate"/>
        <xsl:text>)</xsl:text>
      </td>

      <!-- Latency cells: p50, p95, p99 -->
      <xsl:call-template name="latency-cell"><xsl:with-param name="label">p50</xsl:with-param></xsl:call-template>
      <xsl:call-template name="latency-cell"><xsl:with-param name="label">p95</xsl:with-param></xsl:call-template>
      <xsl:call-template name="latency-cell"><xsl:with-param name="label">p99</xsl:with-param></xsl:call-template>

      <td>
        <xsl:value-of select="v:execution/@samples-executed"/>
        <xsl:text>/</xsl:text>
        <xsl:value-of select="v:execution/@planned-samples"/>
      </td>
      <td><xsl:call-template name="format-elapsed"/></td>
    </tr>

    <!-- Expandable detail row -->
    <tr class="detail-row">
      <td colspan="8">
        <details>
          <summary>Details</summary>
          <xsl:call-template name="verdict-detail"/>
          <xsl:call-template name="misalignment-guidance"/>
          <xsl:call-template name="warnings-box"/>
          <xsl:call-template name="statistical-detail"/>
        </details>
      </td>
    </tr>
  </xsl:template>

  <!-- ===================================================================
       Latency cell
       =================================================================== -->

  <xsl:template name="latency-cell">
    <xsl:param name="label"/>
    <xsl:choose>
      <xsl:when test="v:latency/v:evaluations/v:evaluation[@percentile=$label]">
        <xsl:variable name="eval" select="v:latency/v:evaluations/v:evaluation[@percentile=$label]"/>
        <xsl:variable name="css">
          <xsl:choose>
            <xsl:when test="$eval/@status='PASS'">latency-pass</xsl:when>
            <xsl:when test="$eval/@status='STRICT_FAIL'">latency-fail</xsl:when>
            <xsl:when test="$eval/@status='ADVISORY_WARN'">latency-warn</xsl:when>
            <xsl:otherwise>latency-infeasible</xsl:otherwise>
          </xsl:choose>
        </xsl:variable>
        <td class="{$css}">
          <xsl:choose>
            <xsl:when test="$eval/@observed-ms">
              <xsl:value-of select="$eval/@observed-ms"/><xsl:text>ms</xsl:text>
            </xsl:when>
            <xsl:otherwise>&#x2014;</xsl:otherwise>
          </xsl:choose>
        </td>
      </xsl:when>
      <xsl:otherwise>
        <td class="latency-na">&#x2014;</td>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- ===================================================================
       Level 2: verdict detail
       =================================================================== -->

  <xsl:template name="verdict-detail">
    <pre class="level2">
      <xsl:text>Verdict: </xsl:text>
      <xsl:value-of select="v:verdict/@value"/>
      <xsl:text> &#x2014; </xsl:text>
      <xsl:value-of select="v:verdict/@reason"/>
      <xsl:text>&#10;</xsl:text>
      <xsl:text>Intent:  </xsl:text>
      <xsl:value-of select="v:execution/@intent"/>
      <xsl:text>&#10;</xsl:text>
      <xsl:text>Functional: </xsl:text>
      <xsl:value-of select="v:functional/@successes"/>
      <xsl:text>/</xsl:text>
      <xsl:value-of select="v:functional/@successes + v:functional/@failures"/>
      <xsl:text> (</xsl:text>
      <xsl:value-of select="v:functional/@pass-rate"/>
      <xsl:text>)</xsl:text>
      <xsl:if test="v:statistics">
        <xsl:text>&#10;Threshold: </xsl:text>
        <xsl:value-of select="v:statistics/@threshold"/>
      </xsl:if>
      <xsl:if test="v:latency">
        <xsl:text>&#10;&#10;Latency (</xsl:text>
        <xsl:value-of select="v:latency/@successful-samples"/>
        <xsl:text> samples):&#10;</xsl:text>
        <xsl:for-each select="v:latency/v:evaluations/v:evaluation">
          <xsl:text>  </xsl:text>
          <xsl:value-of select="@percentile"/>
          <xsl:text>: </xsl:text>
          <xsl:choose>
            <xsl:when test="@observed-ms">
              <xsl:value-of select="@observed-ms"/><xsl:text>ms</xsl:text>
            </xsl:when>
            <xsl:otherwise>&#x2014;</xsl:otherwise>
          </xsl:choose>
          <xsl:text> / </xsl:text>
          <xsl:value-of select="@threshold-ms"/><xsl:text>ms</xsl:text>
          <xsl:text> [</xsl:text><xsl:value-of select="@status"/><xsl:text>]</xsl:text>
          <xsl:text>&#10;</xsl:text>
        </xsl:for-each>
      </xsl:if>
    </pre>
  </xsl:template>

  <!-- ===================================================================
       Misalignment guidance
       =================================================================== -->

  <xsl:template name="misalignment-guidance">
    <xsl:if test="v:covariates/@aligned='false' and v:covariates/v:misalignment">
      <div class="misalignment-box">
        <strong>Covariate misalignment detected</strong>
        <p>The baseline was measured under different conditions. Statistical comparison may be unreliable.</p>
        <ul>
          <xsl:for-each select="v:covariates/v:misalignment">
            <li>
              <strong><xsl:value-of select="@key"/></strong>
              <xsl:text>: baseline = </xsl:text>
              <xsl:value-of select="@baseline-value"/>
              <xsl:text>, observed = </xsl:text>
              <xsl:value-of select="@observed-value"/>
            </li>
          </xsl:for-each>
        </ul>
      </div>
    </xsl:if>
  </xsl:template>

  <!-- ===================================================================
       Warnings
       =================================================================== -->

  <xsl:template name="warnings-box">
    <xsl:for-each select="v:warnings/v:warning">
      <div class="warning-box">
        <strong>[<xsl:value-of select="@code"/>]</strong>
        <xsl:text> </xsl:text>
        <xsl:value-of select="."/>
      </div>
    </xsl:for-each>
  </xsl:template>

  <!-- ===================================================================
       Level 3: statistical analysis
       =================================================================== -->

  <xsl:template name="statistical-detail">
    <xsl:if test="v:statistics">
      <details>
        <summary>Statistical analysis</summary>
        <pre class="level3">
          <xsl:text>Confidence level: </xsl:text>
          <xsl:value-of select="v:statistics/@confidence-level"/>
          <xsl:text>&#10;CI bounds: [</xsl:text>
          <xsl:value-of select="v:statistics/@ci-lower"/>
          <xsl:text>, </xsl:text>
          <xsl:value-of select="v:statistics/@ci-upper"/>
          <xsl:text>]&#10;</xsl:text>
          <xsl:text>Standard error: </xsl:text>
          <xsl:value-of select="v:statistics/@standard-error"/>
          <xsl:text>&#10;Threshold: </xsl:text>
          <xsl:value-of select="v:statistics/@threshold"/>
          <xsl:text> (</xsl:text>
          <xsl:value-of select="v:statistics/@threshold-origin"/>
          <xsl:text>)</xsl:text>
          <xsl:if test="v:statistics/@test-statistic">
            <xsl:text>&#10;z-statistic: </xsl:text>
            <xsl:value-of select="v:statistics/@test-statistic"/>
          </xsl:if>
          <xsl:if test="v:statistics/@p-value">
            <xsl:text>&#10;p-value: </xsl:text>
            <xsl:value-of select="v:statistics/@p-value"/>
          </xsl:if>
          <xsl:if test="v:provenance">
            <xsl:text>&#10;</xsl:text>
            <xsl:if test="v:provenance/@spec-filename">
              <xsl:text>&#10;Spec: </xsl:text>
              <xsl:value-of select="v:provenance/@spec-filename"/>
            </xsl:if>
            <xsl:if test="v:provenance/@contract-ref">
              <xsl:text>&#10;Contract: </xsl:text>
              <xsl:value-of select="v:provenance/@contract-ref"/>
            </xsl:if>
          </xsl:if>
          <xsl:if test="v:baseline">
            <xsl:text>&#10;</xsl:text>
            <xsl:text>&#10;Baseline: </xsl:text>
            <xsl:value-of select="v:baseline/@source-file"/>
            <xsl:text>&#10;  Measured: </xsl:text>
            <xsl:value-of select="v:baseline/@generated-at"/>
            <xsl:text>, </xsl:text>
            <xsl:value-of select="v:baseline/@samples"/>
            <xsl:text> samples</xsl:text>
            <xsl:text>&#10;  Baseline rate: </xsl:text>
            <xsl:value-of select="v:baseline/@baseline-rate"/>
            <xsl:text>&#10;  Derived threshold: </xsl:text>
            <xsl:value-of select="v:baseline/@derived-threshold"/>
          </xsl:if>
        </pre>
      </details>
    </xsl:if>
  </xsl:template>

  <!-- ===================================================================
       Elapsed time formatter
       =================================================================== -->

  <xsl:template name="format-elapsed">
    <xsl:variable name="ms" select="v:execution/@elapsed-ms"/>
    <xsl:choose>
      <xsl:when test="$ms &lt; 1000">
        <xsl:value-of select="$ms"/><xsl:text>ms</xsl:text>
      </xsl:when>
      <xsl:otherwise>
        <xsl:value-of select="format-number($ms div 1000, '0.0')"/><xsl:text>s</xsl:text>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- ===================================================================
       CSS (embedded)
       =================================================================== -->

  <xsl:template name="css">
    <style>
    :root {
      --pass-color: #2e7d32;
      --fail-color: #c62828;
      --inconclusive-color: #6a1b9a;
      --advisory-color: #f9a825;
      --border-color: #dee2e6;
      --bg-light: #f8f9fa;
      --bg-white: #ffffff;
      --text-color: #212529;
      --text-muted: #6c757d;
    }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      color: var(--text-color);
      background: var(--bg-light);
      line-height: 1.5;
      padding: 2rem;
    }
    header, main, footer { max-width: 1200px; margin: 0 auto; }
    h1 { font-size: 1.5rem; margin-bottom: 0.25rem; }
    .timestamp { color: var(--text-muted); font-size: 0.875rem; margin-bottom: 0.5rem; }
    .summary-stats {
      font-size: 0.95rem; margin-bottom: 1rem; padding: 0.5rem 0.75rem;
      background: var(--bg-white); border: 1px solid var(--border-color);
      border-radius: 4px; display: inline-block;
    }
    .summary-stats .pass { color: var(--pass-color); font-weight: 600; }
    .summary-stats .fail { color: var(--fail-color); font-weight: 600; }
    .summary-stats .inconclusive { color: var(--inconclusive-color); font-weight: 600; }
    .inconclusive-banner {
      background: #f3e5f5; border-left: 4px solid var(--inconclusive-color);
      padding: 0.75rem 1rem; margin: 1rem 0; font-size: 0.9rem;
    }
    .assumptions { margin: 1rem auto; max-width: 1200px; }
    .assumptions summary { color: var(--text-muted); cursor: pointer; font-size: 0.875rem; }
    .assumptions .content {
      font-size: 0.85rem; color: var(--text-muted); padding: 0.75rem 1rem;
      background: var(--bg-white); border: 1px solid var(--border-color);
      border-radius: 4px; margin-top: 0.5rem;
    }
    .assumptions ul { margin-left: 1.25rem; }
    .assumptions li { margin-bottom: 0.25rem; }
    .test-group { margin-bottom: 2rem; }
    .test-group h2 {
      font-size: 1.15rem; margin-bottom: 0.5rem; padding-bottom: 0.25rem;
      border-bottom: 2px solid var(--border-color);
    }
    table { width: 100%; border-collapse: collapse; background: var(--bg-white); font-size: 0.875rem; }
    thead th {
      background: var(--bg-light); border: 1px solid var(--border-color);
      padding: 0.5rem 0.75rem; text-align: left; font-weight: 600;
    }
    tbody td { border: 1px solid var(--border-color); padding: 0.5rem 0.75rem; vertical-align: top; }
    .verdict-pass { color: var(--pass-color); font-weight: 600; }
    .verdict-fail { color: var(--fail-color); font-weight: 600; }
    .verdict-inconclusive { color: var(--inconclusive-color); font-weight: 600; }
    .latency-pass { color: var(--pass-color); }
    .latency-fail { color: var(--fail-color); }
    .latency-warn { color: var(--advisory-color); }
    .latency-infeasible { color: var(--text-muted); }
    .latency-na { color: var(--text-muted); }
    .detail-row td { padding: 0; border-top: none; }
    .detail-row details { padding: 0.75rem 1rem; }
    .detail-row summary { cursor: pointer; font-size: 0.85rem; color: var(--text-muted); }
    pre.level2, pre.level3 {
      font-family: 'SF Mono', 'Consolas', 'Liberation Mono', monospace;
      font-size: 0.8rem; line-height: 1.6; padding: 0.75rem 1rem; margin: 0.5rem 0;
      background: var(--bg-light); border: 1px solid var(--border-color);
      border-radius: 4px; white-space: pre-wrap; word-break: break-word;
    }
    .warning-box {
      background: #fff8e1; border-left: 4px solid var(--advisory-color);
      padding: 0.5rem 0.75rem; margin: 0.5rem 0; font-size: 0.8rem;
    }
    .misalignment-box {
      background: #f3e5f5; border-left: 4px solid var(--inconclusive-color);
      padding: 0.5rem 0.75rem; margin: 0.5rem 0; font-size: 0.8rem;
    }
    footer {
      text-align: center; color: var(--text-muted); font-size: 0.8rem;
      margin-top: 2rem; padding-top: 1rem; border-top: 1px solid var(--border-color);
    }
    </style>
  </xsl:template>

</xsl:stylesheet>
